[formatter.haskell]
command = "ormolu"
options = [
  "--ghc-opt", "-XBangPatterns",
  "--ghc-opt", "-XPatternSynonyms",
  "--ghc-opt", "-XTypeApplications",
  "--mode", "inplace",
  "--check-idempotence",
]
includes = ["*.hs"]

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.cabal]
command = "cabal-fmt"
options = ["--inplace"]
includes = ["*.cabal"]
