[package]
name = "chatgpt_deez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chatgpt_rs = "*"
tokio = { version = "*", features = ["full"] }
serde = "*"
serde_json = "*"
dotenv = "*"
