require("lexer")

local lexer = Lexer{[[
let five = 5;
    let ten = 10;
    let add = fn(x, y) {
        x + y;
    };
    let result = add(five, ten);
!-/*5;
5 < 10 > 5;
if (5 < 10) {
    return true;
} else {
    return false;
}

10 == 10;
10 != 9;
]], 1, 1, 0}

lexer:ReadChar()

local token = lexer:NextToken()

while token.Type ~= TokenType.Eof do
    print(token.Literal)
    token = lexer:NextToken()
end

print(token.Literal)
