"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TokenType = void 0;
var TokenType;
(function (TokenType) {
    TokenType[TokenType["Illegal"] = 0] = "Illegal";
    TokenType[TokenType["Eof"] = 1] = "Eof";
    TokenType[TokenType["Ident"] = 2] = "Ident";
    TokenType[TokenType["Int"] = 3] = "Int";
    TokenType[TokenType["Assign"] = 4] = "Assign";
    TokenType[TokenType["Plus"] = 5] = "Plus";
    TokenType[TokenType["Dash"] = 6] = "Dash";
    TokenType[TokenType["Bang"] = 7] = "Bang";
    TokenType[TokenType["Asterisk"] = 8] = "Asterisk";
    TokenType[TokenType["ForwardSlash"] = 9] = "ForwardSlash";
    TokenType[TokenType["LessThan"] = 10] = "LessThan";
    TokenType[TokenType["GreaterThan"] = 11] = "GreaterThan";
    TokenType[TokenType["Equal"] = 12] = "Equal";
    TokenType[TokenType["NotEqual"] = 13] = "NotEqual";
    TokenType[TokenType["Comma"] = 14] = "Comma";
    TokenType[TokenType["Semicolon"] = 15] = "Semicolon";
    TokenType[TokenType["LParen"] = 16] = "LParen";
    TokenType[TokenType["RParen"] = 17] = "RParen";
    TokenType[TokenType["LSquirly"] = 18] = "LSquirly";
    TokenType[TokenType["RSquirly"] = 19] = "RSquirly";
    TokenType[TokenType["Function"] = 20] = "Function";
    TokenType[TokenType["Let"] = 21] = "Let";
    TokenType[TokenType["True"] = 22] = "True";
    TokenType[TokenType["False"] = 23] = "False";
    TokenType[TokenType["If"] = 24] = "If";
    TokenType[TokenType["Else"] = 25] = "Else";
    TokenType[TokenType["Return"] = 26] = "Return";
})(TokenType || (exports.TokenType = TokenType = {}));
