const ComplexTypeTag = enum {
    ident,
    integer,
    illegal,
    eof,
    int,
    assign,
    plus,
    comma,
    semicolon,
    lparen,
    rparen,
    lbrace,
    rbrace,
    function,
    let,
};

const ComplexType = union(ComplexTypeTag) {
    ident: []const u8,
    integer: []const u8,
    illegal: []const u8,
    eof: []const u8,
    int: []const u8,
    assign: []const u8,
    plus: []const u8,
    comma: []const u8,
    semicolon: []const u8,
    lparen: []const u8,
    rparen: []const u8,
    lbrace: []const u8,
    rbrace: []const u8,
    function: []const u8,
    let: []const u8,
};
